### PR TITLE
Add example style sheet in README

### PR DESCRIPTION
**Pull request by IgnaceMaes**
Awesome work on this!

I was going through the code example in the `embroider-css-modules` package and missed the context of the actual CSS file. To get the full picture of the addon, I had a look in the [docs app](https://github.com/ijlee2/embroider-css-modules/tree/main/docs-app).

Not sure if the `d.ts` file should be mentioned as well?

Also pretty cool that styles can be co-located and depend on module resolution. That's perhaps something that can use a further mention as well?

### CODE REVIEW

**Comment by ijlee2** [comment]
Thanks for providing feedback and working on updating the `README`.

I agree with the sentiment, as I realized yesterday that the current `README`'s assume too much. Namely, if a developer hasn't used CSS modules or `ember-css-modules` before, they would be lost on how to set up their project and write CSS files. I think [`ember-css-modules` did a good job on onboarding users](https://github.com/salsify/ember-css-modules/#usage).

I'm not sure yet if where you placed the CSS example is where it will end up eventually. Nonetheless, let's go ahead with the addition and iterate on the `README`'s.

**Review by ijlee2 — APPROVED** [review]

**Comment by IgnaceMaes** [comment]
> > styles can [...] depend on module resolution. That's perhaps something that can use a further mention as well?
> 
> I didn't understand the first sentence fully. Can you explain to me what you had in mind with regards to the further mention?

Using this addon, styles are using (explicit) imports. That's a pretty significant difference compared to most other solutions which just have implicit linking like e.g. requiring a file with a `.css` extension in the same folder as the component.

With this approach you have the option to still do that (co-locate the CSS) or put it in a totally separate folder? If I understand correctly. (I've yet to actually try the addon 😄)

**Comment by IgnaceMaes** [comment]
> > styles can [...] depend on module resolution. That's perhaps something that can use a further mention as well?
> 
> I didn't understand the first sentence fully. Can you explain to me what you had in mind with regards to the further mention?

Using this addon, styles are using (explicit) imports. That's a pretty significant difference compared to most other solutions which just have implicit linking like e.g. requiring a file with a `.css` extension in the same folder as the component.

With this approach you have the option to still do that (co-locate the CSS) or put it in a totally separate folder? If I understand correctly. (I've yet to actually try the addon 😄)

**Comment by ijlee2** [comment]
> With this approach you have the option to still do that (co-locate the CSS) or put it in a totally separate folder?

@IgnaceMaes Ah, I think I understand now, thanks for the clarification.

Yep, you are free to place the stylesheets wherever you'd like ([with the exception of the `styles` folder](https://github.com/evoactivity/ember-modern-css#legacy-styles-and-stylesappcss); importing a css file inside that folder doesn't seem to work) and name the files however you'd like.

The provided codemod and the `docs-app` have placed and named the `*.css` files to more closely match a project that a developer would have had with `ember-css-modules`. Help ease the transition this way.

I will keep the file name and location in mind when I update the `README`'s.

**Comment by IgnaceMaes** [comment]
@ijlee2 Yes, that's indeed what I was referring to.

A section on how it compares to other CSS solutions for Ember would be interesting, and could include something like this. But that's perhaps part of the README's onboarding effort which you mentioned in the first comment.

> The provided codemod and the docs-app have placed and named the *.css files to more closely match a project that a developer would have had with ember-css-modules. Help ease the transition this way.

That also seems like a logical way of doing it to me!

**Pull request merged**
